[m5stack]
extends = esp32
board = m5stack-fire
upload_port = COM6
monitor_port = COM6
lib_deps = 
	${esp32.lib_deps}
	${libraries.m5stack}
build_flags = ${esp32.build_flags}
	-D M5STACK_FIRE
	-D FIRMWARE_TARGET=\"m5stack-fire\"
	-D HAS_DISPLAY=1
	-D COM=Serial2
	-D RX_PIN=GPIO_NUM_16
	-D TX_PIN=GPIO_NUM_17

[env:wemos_d1_mini32]
extends = esp32
board = wemos_d1_mini32
; upload_port = COM6
; monitor_port = COM6
build_flags = ${esp32.build_flags}
	-D WEMOS_D1_ESP32
	-D FIRMWARE_TARGET=\"wemos_d1_mini32\"
	-D COM=Serial2
	-D RX_PIN=GPIO_NUM_16
	-D TX_PIN=GPIO_NUM_17
lib_deps = 
	${esp32.lib_deps}
	${lib_deps_esp32.node}

[env:wemos_d1_mini32_control]
extends = env:wemos_d1_mini32
build_flags = ${env:wemos_d1_mini32.build_flags}
	-D MQTT_NOW_CONTROLLER=1
lib_deps = 
	${esp32.lib_deps}
	${lib_deps_esp32.node}

[env:wemos_d1_mini32_client]
extends = env:wemos_d1_mini32
build_flags = ${env:wemos_d1_mini32.build_flags}
	-D MQTT_NOW_CLIENT=1
lib_deps = 
	${esp32.lib_deps}
	${lib_deps_esp32.client}

[env:wemos_d1_mini32_test]
extends = env:wemos_d1_mini32
build_flags = ${env:wemos_d1_mini32.build_flags}
	-D MQTT_TEST_COMPILE=1
lib_deps = 
	${esp32.lib_deps}
	${lib_deps_esp32.node}
	${lib_deps_esp32.client}

[env:esp32doit-devkit-v1]
extends = esp32
board = esp32doit-devkit-v1
upload_port = COM5
monitor_port = COM5
build_flags = ${esp32.build_flags}
	-D ESP32DOIT_DEVKIT_V1
	-D FIRMWARE_TARGET=esp32doit-devkit-v1
	-D COM=Serial2
	-D RX_PIN=GPIO_NUM_16
	-D TX_PIN=GPIO_NUM_17
lib_deps = 
	${esp32.lib_deps}
	${lib_deps_esp32.node}

[env:m5stack-fire]
extends = m5stack
lib_deps = 
	${m5stack.lib_deps}
	${lib_deps_esp32.node}
build_flags = ${m5stack.build_flags}
	
[env:m5stack-fire-client] 
extends = m5stack
lib_deps = 
	${m5stack.lib_deps}
	${lib_deps_esp32.client}
build_flags = 
	${m5stack.build_flags}
	-D MQTT_NOW_CLIENT=1
	-D DEVNAME=M5Client

[env:m5stack-fire-control]
extends = m5stack
lib_deps = 
	${m5stack.lib_deps}
build_flags = 
	${m5stack.build_flags}
	-D MQTT_NOW_CONTROLLER=1

[esp32c3-mini]
extends = esp32
board = esp32-c3-devkitm-1
build_flags = ${esp32.build_flags}
	-D TENSTAR_ESP32C3
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D COM=Serial0
	-D RX_PIN=GPIO_NUM_6
	-D TX_PIN=GPIO_NUM_7
lib_deps = 
	${esp32.lib_deps}
	${lib_deps_esp32.node}

[nodemcu-32s]
extends = esp32
board = nodemcu-32s
upload_port = COM5
monitor_port = COM5
build_flags = ${esp32.build_flags}
	

[env:nodemcu-32s-control-bridge]
extends = nodemcu-32s
build_flags = ${nodemcu-32s.build_flags}
	-D FIRMWARE_TARGET=\"nodemcu-32s-control-bridge\"
	-D MQTT_NOW_CONTROLLER=1
	-D MQTT_NOW_BRIDGE=1

[env:esp32c3-mini]
extends = esp32c3-mini
build_flags = ${esp32c3-mini.build_flags}
	-D FIRMWARE_TARGET=\"tenstar-robot-esp32-c3-mini\"
	
[env:esp32c3-mini-control]
extends = esp32c3-mini
upload_port = COM4
monitor_port = COM4
build_flags = ${esp32c3-mini.build_flags}
	-D FIRMWARE_TARGET=\"tenstar-robot-esp32-c3-mini-control\"
	-D MQTT_NOW_CONTROLLER=1

[env:esp32c3-mini-control-bridge]
extends = esp32c3-mini
upload_port = COM4
monitor_port = COM4
build_flags = ${esp32c3-mini.build_flags}
	-D FIRMWARE_TARGET=\"tenstar-robot-esp32-c3-mini-control-bridge\"
	-D MQTT_NOW_CONTROLLER=1
	-D MQTT_NOW_BRIDGE=1


[env:esp32c3-mini-oled-control]
extends = esp32c3-mini
upload_port = COM4
monitor_port = COM4
build_flags = ${esp32c3-mini.build_flags}
	-D FIRMWARE_TARGET=\"tenstar-robot-esp32-c3-mini-control\"
	-D MQTT_NOW_CONTROLLER=1
	-D HAS_DISPLAY=1

[env:esp32c3-mini-client]
extends = esp32c3-mini
upload_port = COM3
monitor_port = COM3
build_flags = ${esp32c3-mini.build_flags}
	-D FIRMWARE_TARGET=\"tenstar-robot-esp32-c3-mini-client\"
	-D MQTT_NOW_CLIENT=1
	-D HASS_AUTODISCOVER=1
lib_deps = 
	${esp32c3-mini.lib_deps}
	${lib_deps_esp32.client}